baseURL = 'https://luuhai48.github.io/'
languageCode = 'en-us'
title = 'Lưu Viết Hải - A Coding Guy'
theme = 'hugo-theme-stack'

[Params.sidebar]
  subtitle = 'Trying to make the code runs'
  emoji = '💆'

[Params.sidebar.avatar]
  src = 'img/avatar.jpg'
