baseURL = 'https://luuhai48.com'
languageCode = 'en-us'
title = 'A Coding Guy'
description = "I'm trying to make the code runs"
paginate = 10
disqusShortname = 'luuhai48'

[services.rss]
  limit = 20

[Author]
  name = "luuhai48"
  email = "luuhai.hn48@gmail.com"

[permalinks]
  posts = "/posts/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  page = ["html"]
  home = ["html"]
  section = ["html","rss"]
  taxonomyTerm = ["html"]
  taxonomy = ["html"]

[markup.highlight]
  noClasses = false
  linenos = true
